# Generated by Django 5.2.15 on 2026-06-08 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('record_number', models.CharField(max_length=30)),
                ('blood_type', models.CharField(blank=True, max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_diseases', models.TextField(blank=True)),
                ('surgical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='clinics.clinic')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='patients.patient')),
            ],
            options={
                'ordering': ['record_number'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('consultation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('physical_exam', models.TextField(blank=True)),
                ('clinical_assessment', models.TextField(blank=True)),
                ('preliminary_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('void_reason', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='doctors.doctorprofile')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_finalized', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-consultation_date', '-start_time', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glucose', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='medical_records.clinicalconsultation')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vital signs',
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['clinic', 'record_number'], name='medical_rec_clinic__5ce36b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient'], name='medical_rec_patient_338240_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['activo'], name='medical_rec_activo_dba871_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalrecord',
            constraint=models.UniqueConstraint(fields=('clinic', 'record_number'), name='unique_record_number_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='clinicalconsultation',
            index=models.Index(fields=['clinic', 'consultation_date'], name='medical_rec_clinic__ec02f7_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalconsultation',
            index=models.Index(fields=['patient', 'consultation_date'], name='medical_rec_patient_206591_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalconsultation',
            index=models.Index(fields=['doctor', 'consultation_date'], name='medical_rec_doctor__2f237e_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalconsultation',
            index=models.Index(fields=['status'], name='medical_rec_status_4f6729_idx'),
        ),
    ]
