# Generated by Django 5.2.15 on 2026-06-11 16:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('billing', '0003_invoiceitem_inventory_item_invoiceitem_inventory_lot_and_more'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('inventory', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSupplyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usage_type', models.CharField(choices=[('medication', 'Medicamento'), ('supply', 'Insumo'), ('procedure_supply', 'Insumo de procedimiento'), ('injection', 'Inyeccion'), ('serum', 'Suero'), ('wound_care', 'Curacion'), ('nebulization', 'Nebulizacion'), ('other', 'Otro')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('billable', models.BooleanField(default=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicado'), ('cancelled', 'Cancelado'), ('invoiced', 'Facturado')], default='applied', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_supply_usages', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_usages', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_supply_usages', to='clinics.clinic')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_usages', to='medical_records.clinicalconsultation')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_usages', to='doctors.doctorprofile')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_usages', to='inventory.inventoryitem')),
                ('inventory_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_usages', to='inventory.inventorylot')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_consumptions', to='inventory.inventorymovement')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_consumptions', to='billing.invoice')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_consumptions', to='billing.invoiceitem')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_supply_usages', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_supply_usages', to='patients.patient')),
            ],
            options={
                'ordering': ['-applied_at', '-creado_en'],
                'indexes': [models.Index(fields=['clinic', 'applied_at'], name='medical_rec_clinic__bc131e_idx'), models.Index(fields=['patient', 'applied_at'], name='medical_rec_patient_d25bf6_idx'), models.Index(fields=['consultation', 'status'], name='medical_rec_consult_c4ac24_idx'), models.Index(fields=['billable', 'invoiced', 'status'], name='medical_rec_billabl_1e9b2b_idx')],
            },
        ),
    ]
