# Generated by Django 5.2.15 on 2026-06-11 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('medical_records', '0002_clinicalsupplyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalconsultation',
            name='patient_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='admissions.patientvisit'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='pain_scale',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='patient_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='admissions.patientvisit'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='medical_records.clinicalconsultation'),
        ),
    ]
