# Generated by Django 5.2.15 on 2026-07-24 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_patientvisit_unique_visit_per_appointment'),
        ('appointments', '0002_appointment_modality'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('medical_records', '0003_clinicalconsultation_patient_visit_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalconsultation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='clinicalconsultation',
            constraint=models.UniqueConstraint(fields=('patient_visit',), name='unique_consultation_per_visit'),
        ),
    ]
