# Generated by Django 5.2.15 on 2026-07-25 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_modality'),
        ('billing', '0008_creditnote'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('inventory', '0001_initial'),
        ('medical_records', '0004_clinicalconsultation_version_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsupplyusage',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinicalsupplyusage',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsupplyusage',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_clinical_supply_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalsupplyusage',
            name='consumption_group',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='clinicalsupplyusage',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='clinicalsupplyusage',
            constraint=models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_clinical_consumption_idempotency_per_clinic'),
        ),
    ]
