# Generated by Django 5.2.15 on 2026-07-30 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalization', '0004_dischargesummary_and_more'),
        ('medical_records', '0005_clinicalsupplyusage_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsupplyusage',
            name='hospitalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_supply_usages', to='hospitalization.hospitalization'),
        ),
        migrations.AddField(
            model_name='clinicalsupplyusage',
            name='medication_administration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_supply_usages', to='hospitalization.medicationadministration'),
        ),
    ]
