# Generated by Django 5.2.15 on 2026-06-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='billableservice',
            name='unique_service_code_per_clinic',
        ),
        migrations.AddConstraint(
            model_name='billableservice',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('clinic', 'code'), name='unique_service_code_per_clinic'),
        ),
    ]
