# Generated by Django 5.2.15 on 2026-06-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_billableservice_unique_service_code_per_clinic_and_more'),
        ('inventory', '0001_initial'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='inventory_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='inventory_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Servicio'), ('inventory_item', 'Producto de inventario'), ('medication', 'Medicamento'), ('supply', 'Insumo'), ('procedure', 'Procedimiento'), ('consumption', 'Consumo clinico'), ('manual', 'Manual')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='related_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='medical_records.clinicalconsultation'),
        ),
    ]
