# Generated by Django 5.2.15 on 2026-06-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoiceitem_inventory_item_invoiceitem_inventory_lot_and_more'),
        ('medical_records', '0002_clinicalsupplyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='related_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='medical_records.clinicalsupplyusage'),
        ),
    ]
