# Generated by Django 5.2.15 on 2026-06-18 00:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_modality'),
        ('billing', '0004_invoiceitem_related_consumption'),
        ('clinics', '0001_initial'),
        ('medical_records', '0003_clinicalconsultation_patient_visit_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicFiscalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=180)),
                ('commercial_name', models.CharField(blank=True, max_length=180)),
                ('rtn', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('municipality', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('economic_activity', models.CharField(blank=True, max_length=180)),
                ('is_fiscal_billing_enabled', models.BooleanField(default=False)),
                ('default_isv_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('secondary_isv_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('18.00'), max_digits=5, null=True)),
                ('require_customer_rtn', models.BooleanField(default=False)),
                ('fiscal_legend', models.TextField(blank=True, default='La factura es beneficio de todos, exijala.')),
            ],
            options={
                'ordering': ['clinic__nombre'],
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('credit_note', 'Nota de credito'), ('debit_note', 'Nota de debito'), ('receipt', 'Recibo')], default='invoice', max_length=30)),
                ('cai', models.CharField(max_length=80)),
                ('establishment_code', models.CharField(default='000', max_length=3)),
                ('emission_point_code', models.CharField(default='001', max_length=3)),
                ('document_type_code', models.CharField(default='01', max_length=2)),
                ('start_number', models.PositiveIntegerField()),
                ('end_number', models.PositiveIntegerField()),
                ('current_number', models.PositiveIntegerField()),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_exhausted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_active', 'expiration_date'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cai',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_rtn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emitter_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emitter_commercial_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emitter_legal_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emitter_rtn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_range_end',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_range_start',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fiscal_status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('issued', 'Emitida'), ('cancelled', 'Anulada'), ('void', 'Void')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='isv_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='isv_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fiscal_documents', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_exempt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_exonerated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_taxed_15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_taxed_18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_type',
            field=models.CharField(choices=[('taxed_15', 'Gravado 15%'), ('taxed_18', 'Gravado 18%'), ('exempt', 'Exento'), ('exonerated', 'Exonerado')], default='exempt', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('fiscal_number', None), _negated=True), fields=('clinic', 'fiscal_number'), name='unique_fiscal_number_per_clinic'),
        ),
        migrations.AddField(
            model_name='clinicfiscalprofile',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_profile', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentrange',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_document_ranges', to='clinics.clinic'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentrange',
            index=models.Index(fields=['clinic', 'document_type', 'is_active'], name='billing_fis_clinic__c4b839_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentrange',
            index=models.Index(fields=['clinic', 'expiration_date'], name='billing_fis_clinic__d680c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentrange',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_exhausted', False)), fields=('clinic', 'document_type'), name='unique_active_fiscal_range_per_clinic_type'),
        ),
    ]
