# Generated by Django 5.2.15 on 2026-06-18 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_modality'),
        ('billing', '0005_clinicfiscalprofile_fiscaldocumentrange_and_more'),
        ('clinics', '0001_initial'),
        ('medical_records', '0003_clinicalconsultation_patient_visit_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fiscaldocumentrange',
            name='unique_active_fiscal_range_per_clinic_type',
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_fiscal_number_per_clinic',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('clinic', 'fiscal_number'), name='unique_fiscal_number_per_clinic'),
        ),
    ]
