# Generated by Django 5.2.15 on 2026-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_fiscaldocumentrange_unique_active_fiscal_range_per_clinic_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicfiscalprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clinicfiscalprofile',
            name='rtn',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
