# Generated by Django 5.2.15 on 2026-07-07 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_clinicfiscalprofile_address_and_more'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('credit_note_number', models.CharField(max_length=30)),
                ('fiscal_number', models.CharField(max_length=30)),
                ('cai', models.CharField(max_length=80)),
                ('fiscal_range_start', models.CharField(max_length=30)),
                ('fiscal_range_end', models.CharField(max_length=30)),
                ('fiscal_expiration_date', models.DateField()),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('issue_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_exempt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_exonerated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_taxed_15', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_taxed_18', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('isv_15', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('isv_18', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('issued', 'Emitida'), ('cancelled', 'Anulada'), ('voided', 'Void')], default='issued', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_cancelled', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clinics.clinic')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_issued', to=settings.AUTH_USER_MODEL)),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.invoice')),
            ],
            options={
                'ordering': ['-issue_datetime'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'credit_note_number'), name='unique_credit_note_number_per_clinic'), models.UniqueConstraint(fields=('clinic', 'fiscal_number'), name='unique_credit_note_fiscal_number_per_clinic'), models.UniqueConstraint(condition=models.Q(('active', True), ('status', 'issued')), fields=('original_invoice',), name='unique_active_credit_note_per_invoice')],
            },
        ),
    ]
