# Generated by Django 5.2.15 on 2026-07-28 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_creditnote'),
        ('clinics', '0001_initial'),
        ('inventory', '0001_initial'),
        ('medical_records', '0005_clinicalsupplyusage_cancellation_reason_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='method',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('deposito', 'Deposito'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movement', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='reversed_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movements', to='billing.cashmovement'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_id',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('apertura', 'Apertura'), ('pago', 'Pago'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('reverso', 'Reverso'), ('ajuste', 'Ajuste'), ('cierre', 'Cierre')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_cash_movement_idempotency_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'source_type', 'source_id'), name='unique_invoice_item_source'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('clinic', 'idempotency_key'), name='unique_payment_idempotency_per_clinic'),
        ),
    ]
