# Generated by Django 5.2.15 on 2026-07-30 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_cashmovement_idempotency_key_cashmovement_invoice_and_more'),
        ('hospitalization', '0003_medicalevolution_medicalinstruction_treatmentplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hospitalization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_invoice', to='hospitalization.hospitalization'),
        ),
    ]
