# Generated by Django 5.2.15 on 2026-06-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('secondary_color', models.CharField(default='#0F172A', max_length=7)),
                ('accent_color', models.CharField(default='#14B8A6', max_length=7)),
                ('currency', models.CharField(default='HNL', max_length=8)),
                ('country', models.CharField(default='Honduras', max_length=80)),
                ('timezone', models.CharField(default='America/Tegucigalpa', max_length=80)),
                ('language', models.CharField(default='es', max_length=10)),
                ('tax_enabled', models.BooleanField(default=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('invoice_prefix', models.CharField(default='FAC', max_length=12)),
                ('patient_prefix', models.CharField(default='PAC', max_length=12)),
                ('medical_record_prefix', models.CharField(default='EXP', max_length=12)),
                ('prescription_prefix', models.CharField(default='RX', max_length=12)),
                ('purchase_order_prefix', models.CharField(default='PO', max_length=12)),
                ('appointment_duration_minutes', models.PositiveIntegerField(default=30)),
                ('allow_online_appointments', models.BooleanField(default=False)),
                ('allow_patient_cancellations', models.BooleanField(default=True)),
                ('cancellation_hours_limit', models.PositiveIntegerField(default=24)),
                ('require_appointment_confirmation', models.BooleanField(default=False)),
                ('allow_patient_portal', models.BooleanField(default=True)),
                ('allow_patient_medical_record_view', models.BooleanField(default=True)),
                ('allow_patient_prescription_view', models.BooleanField(default=True)),
                ('allow_patient_invoice_view', models.BooleanField(default=True)),
                ('business_start_time', models.TimeField(default='08:00')),
                ('business_end_time', models.TimeField(default='17:00')),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('fiscal_name', models.CharField(blank=True, max_length=180)),
                ('fiscal_rtn', models.CharField(blank=True, max_length=40)),
                ('fiscal_address', models.TextField(blank=True)),
                ('fiscal_phone', models.CharField(blank=True, max_length=40)),
                ('fiscal_email', models.EmailField(blank=True, max_length=254)),
                ('footer_invoice_text', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'Clinic settings',
            },
        ),
    ]
