# Generated by Django 5.2.15 on 2026-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='medical_order_prefix',
            field=models.CharField(default='OM', max_length=12),
        ),
    ]
