# Generated by Django 5.2.15 on 2026-06-18 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_settings', '0002_clinicsettings_medical_order_prefix'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicWorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('allow_walk_in_patients', models.BooleanField(default=True)),
                ('allow_appointments', models.BooleanField(default=True)),
                ('allow_online_appointments', models.BooleanField(default=False)),
                ('allow_in_person_appointments', models.BooleanField(default=True)),
                ('reception_can_create_minimal_patient', models.BooleanField(default=True)),
                ('reception_handles_cashier', models.BooleanField(default=True)),
                ('walk_in_requires_triage', models.BooleanField(default=True)),
                ('appointment_requires_triage', models.BooleanField(default=False)),
                ('appointment_direct_to_doctor', models.BooleanField(default=True)),
                ('billing_before_consultation', models.BooleanField(default=False)),
                ('billing_after_consultation', models.BooleanField(default=True)),
                ('require_payment_before_consultation', models.BooleanField(default=False)),
                ('allow_consultation_without_payment', models.BooleanField(default=True)),
                ('require_identity_for_patient', models.BooleanField(default=False)),
                ('require_phone_for_patient', models.BooleanField(default=False)),
                ('allow_doctor_to_create_patient', models.BooleanField(default=False)),
                ('allow_nurse_to_edit_patient_basic_data', models.BooleanField(default=False)),
                ('auto_send_to_billing_after_consultation', models.BooleanField(default=True)),
                ('auto_complete_visit_after_payment', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'Clinic workflow settings',
            },
        ),
    ]
