export const endpoints = {
  auth: {
    changePassword: '/auth/change-password/',
    login: '/auth/login/',
    me: '/auth/me/',
    refresh: '/auth/refresh/',
    logout: '/auth/logout/',
  },
  patientPortal: {
    dashboard: '/patient-portal/dashboard/',
    profile: '/patient-portal/profile/',
    appointments: '/patient-portal/appointments/',
    appointment: (id: number | string) => `/patient-portal/appointments/${id}/`,
    requestAppointment: '/patient-portal/appointments/request/',
    cancelAppointment: (id: number | string) => `/patient-portal/appointments/${id}/cancel/`,
    specialties: '/patient-portal/specialties/',
    doctors: '/patient-portal/doctors/',
    doctorAvailability: (doctorId: number | string) =>
      `/patient-portal/doctors/${doctorId}/availability/`,
    prescriptions: '/patient-portal/prescriptions/',
    prescription: (id: number | string) => `/patient-portal/prescriptions/${id}/`,
    invoices: '/patient-portal/invoices/',
    invoice: (id: number | string) => `/patient-portal/invoices/${id}/`,
    invoiceFiscalPdf: (id: number | string) => `/patient-portal/invoices/${id}/fiscal-pdf/`,
    documents: '/patient-portal/documents/',
    document: (id: number | string) => `/patient-portal/documents/${id}/`,
    documentDownload: (id: number | string) => `/patient-portal/documents/${id}/download/`,
    documentPreview: (id: number | string) => `/patient-portal/documents/${id}/preview/`,
    notifications: '/patient-portal/notifications/',
    unreadNotifications: '/patient-portal/notifications/unread-count/',
    markNotificationRead: (id: number | string) => `/patient-portal/notifications/${id}/mark-read/`,
    markAllNotificationsRead: '/patient-portal/notifications/mark-all-read/',
    clinicInfo: '/patient-portal/clinic-info/',
    settings: '/patient-portal/settings/',
    payments: '/patient-portal/payments/',
    payment: (id: number | string) => `/patient-portal/payments/${id}/`,
    medicalOrders: '/patient-portal/medical-orders/',
    medicalOrder: (id: number | string) => `/patient-portal/medical-orders/${id}/`,
    medicalRecordSummary: '/patient-portal/medical-record-summary/',
  },
  notifications: {
    list: '/notifications/',
    unreadCount: '/notifications/unread-count/',
    markRead: (id: number | string) => `/notifications/${id}/mark-read/`,
  },
  clinicAdmin: {
    dashboard: '/clinic-admin/dashboard/',
    createStaff: '/clinic-admin/users/create-staff/',
    myClinic: '/clinic-admin/my-clinic/',
    users: '/clinic-admin/users/',
    user: (id: number | string) => `/clinic-admin/users/${id}/`,
    activateUser: (id: number | string) => `/clinic-admin/users/${id}/activate/`,
    deactivateUser: (id: number | string) => `/clinic-admin/users/${id}/deactivate/`,
    clinicReport: '/reports/clinic-dashboard/',
    financialReport: '/reports/financial/',
    appointmentsReport: '/reports/appointments/',
    fiscalReadiness: '/billing/fiscal-readiness/',
    fiscalRanges: '/billing/fiscal-ranges/',
    auditLogs: '/audit/logs/',
    auditSummary: '/audit/summary/',
    doctors: '/doctors/',
    roles: '/roles/',
    specialties: '/specialties/',
    subscription: '/subscriptions/my-subscription/',
    usage: '/subscriptions/usage/',
  },
  doctor: {
    dashboard: '/doctor/dashboard/',
    dashboardAlt: '/medical/doctor/dashboard/',
    scheduleToday: '/doctor/schedule/today/',
    appointments: '/doctor/appointments/',
    appointmentsDoctorAlt: '/appointments/doctor/',
    appointmentsAlt: '/appointments/',
    appointment: (id: number | string) => `/doctor/appointments/${id}/`,
    waitingRoom: '/doctor/waiting-room/',
    waitingRoomAlt: '/admissions/doctor-waiting-room/',
    waitingRoomVisitsAlt: '/visits/doctor-waiting-room/',
    visits: '/admissions/visits/',
    patientSummary: (id: number | string) => `/doctor/patients/${id}/summary/`,
    patientSummaryAlt: (id: number | string) => `/medical-records/patients/${id}/summary/`,
    visit: (id: number | string) => `/admissions/visits/${id}/`,
    visitAlt: (id: number | string) => `/doctor/visits/${id}/`,
    vitalSigns: (visitId: number | string) => `/admissions/visits/${visitId}/vital-signs/`,
    vitalSignsAlt: '/medical/vital-signs/',
    triage: (visitId: number | string) => `/admissions/visits/${visitId}/triage/`,
    startConsultation: (visitId: number | string) =>
      `/admissions/visits/${visitId}/start-consultation/`,
    completeConsultation: (visitId: number | string) =>
      `/admissions/visits/${visitId}/complete-consultation/`,
    consultations: '/consultations/',
    consultation: (id: number | string) => `/consultations/${id}/`,
    patientConsultations: (patientId: number | string) => `/medical-records/patients/${patientId}/consultations/`,
    patientConsultationsAlt: (patientId: number | string) => `/patients/${patientId}/consultations/`,
    consultationDiagnoses: (id: number | string) => `/consultations/${id}/diagnoses/`,
    consultationPrescriptions: (id: number | string) => `/consultations/${id}/prescriptions/`,
    prescriptions: '/prescriptions/',
    consultationMedicalOrders: (id: number | string) => `/consultations/${id}/medical-orders/`,
    medicalOrders: '/medical-orders/',
    medicalOrderDocuments: (id: number | string) => `/medical-orders/${id}/documents/`,
    consultationConsumptions: (id: number | string) => `/consultations/${id}/consumptions/`,
    clinicalConsumptions: '/clinical-consumptions/',
    inventoryItems: '/inventory/items/',
    profile: '/doctor/profile/',
    profileAlt: '/doctors/me/',
    schedules: '/doctor/schedules/',
    schedulesAlt: '/doctors/me/schedules/',
    activitySummary: '/doctor/activity-summary/',
  },
  hospitalization: {
    dashboard: '/hospitalization/dashboard/',
    admissions: '/hospitalization/admissions/',
    admission: (id: number | string) => `/hospitalization/admissions/${id}/`,
    vitalSigns: (id: number | string) => `/hospitalization/admissions/${id}/vital-signs/`,
    nursingNotes: (id: number | string) => `/hospitalization/admissions/${id}/nursing-notes/`,
    nursingRounds: (id: number | string) => `/hospitalization/admissions/${id}/nursing-rounds/`,
    medicationAdministrations: (id: number | string) => `/hospitalization/admissions/${id}/medication-administrations/`,
    pendingMedications: '/hospitalization/medications/pending/',
    administerMedication: (id: number | string) => `/hospitalization/medication-administrations/${id}/administer/`,
    omitMedication: (id: number | string) => `/hospitalization/medication-administrations/${id}/omit/`,
    delayMedication: (id: number | string) => `/hospitalization/medication-administrations/${id}/delay/`,
    events: (id: number | string) => `/hospitalization/admissions/${id}/events/`,
    beds: '/hospitalization/beds/',
    availableBeds: '/hospitalization/beds/available/',
  },
} as const;
