export const endpoints = {
  auth: {
    changePassword: '/auth/change-password/',
    login: '/auth/login/',
    me: '/auth/me/',
    refresh: '/auth/refresh/',
    logout: '/auth/logout/',
  },
  patientPortal: {
    dashboard: '/patient-portal/dashboard/',
    profile: '/patient-portal/profile/',
    appointments: '/patient-portal/appointments/',
    appointment: (id: number | string) => `/patient-portal/appointments/${id}/`,
    requestAppointment: '/patient-portal/appointments/request/',
    cancelAppointment: (id: number | string) => `/patient-portal/appointments/${id}/cancel/`,
    specialties: '/patient-portal/specialties/',
    doctors: '/patient-portal/doctors/',
    doctorAvailability: (doctorId: number | string) =>
      `/patient-portal/doctors/${doctorId}/availability/`,
    prescriptions: '/patient-portal/prescriptions/',
    prescription: (id: number | string) => `/patient-portal/prescriptions/${id}/`,
    invoices: '/patient-portal/invoices/',
    invoice: (id: number | string) => `/patient-portal/invoices/${id}/`,
    documents: '/patient-portal/documents/',
    document: (id: number | string) => `/patient-portal/documents/${id}/`,
    documentDownload: (id: number | string) => `/patient-portal/documents/${id}/download/`,
    documentPreview: (id: number | string) => `/patient-portal/documents/${id}/preview/`,
    notifications: '/patient-portal/notifications/',
    unreadNotifications: '/patient-portal/notifications/unread-count/',
    clinicInfo: '/patient-portal/clinic-info/',
    payments: '/patient-portal/payments/',
    medicalOrders: '/patient-portal/medical-orders/',
    medicalOrder: (id: number | string) => `/patient-portal/medical-orders/${id}/`,
  },
  notifications: {
    list: '/notifications/',
    unreadCount: '/notifications/unread-count/',
    markRead: (id: number | string) => `/notifications/${id}/mark-read/`,
  },
  doctor: {
    dashboard: '/doctor/dashboard/',
    dashboardAlt: '/medical/doctor/dashboard/',
    scheduleToday: '/doctor/schedule/today/',
    appointments: '/doctor/appointments/',
    appointmentsDoctorAlt: '/appointments/doctor/',
    appointmentsAlt: '/appointments/',
    appointment: (id: number | string) => `/doctor/appointments/${id}/`,
    waitingRoom: '/doctor/waiting-room/',
    waitingRoomAlt: '/admissions/doctor-waiting-room/',
    waitingRoomVisitsAlt: '/visits/doctor-waiting-room/',
    visits: '/admissions/visits/',
    patientSummary: (id: number | string) => `/doctor/patients/${id}/summary/`,
    patientSummaryAlt: (id: number | string) => `/medical-records/patients/${id}/summary/`,
    visit: (id: number | string) => `/admissions/visits/${id}/`,
    visitAlt: (id: number | string) => `/doctor/visits/${id}/`,
    vitalSigns: (visitId: number | string) => `/admissions/visits/${visitId}/vital-signs/`,
    vitalSignsAlt: '/medical/vital-signs/',
    triage: (visitId: number | string) => `/admissions/visits/${visitId}/triage/`,
    startConsultation: (visitId: number | string) =>
      `/admissions/visits/${visitId}/start-consultation/`,
    completeConsultation: (visitId: number | string) =>
      `/admissions/visits/${visitId}/complete-consultation/`,
    consultations: '/consultations/',
    consultation: (id: number | string) => `/consultations/${id}/`,
    consultationDiagnoses: (id: number | string) => `/consultations/${id}/diagnoses/`,
    consultationPrescriptions: (id: number | string) => `/consultations/${id}/prescriptions/`,
    prescriptions: '/prescriptions/',
    consultationMedicalOrders: (id: number | string) => `/consultations/${id}/medical-orders/`,
    medicalOrders: '/medical-orders/',
    consultationConsumptions: (id: number | string) => `/consultations/${id}/consumptions/`,
    clinicalConsumptions: '/clinical-consumptions/',
    inventoryItems: '/inventory/items/',
    profile: '/doctor/profile/',
  },
} as const;
