export const endpoints = {
  auth: {
    login: '/auth/login/',
    me: '/auth/me/',
    refresh: '/auth/refresh/',
  },
  patientPortal: {
    dashboard: '/patient-portal/dashboard/',
    profile: '/patient-portal/profile/',
    appointments: '/patient-portal/appointments/',
    appointment: (id: number | string) => `/patient-portal/appointments/${id}/`,
    requestAppointment: '/patient-portal/appointments/request/',
    cancelAppointment: (id: number | string) => `/patient-portal/appointments/${id}/cancel/`,
    specialties: '/patient-portal/specialties/',
    doctors: '/patient-portal/doctors/',
    doctorAvailability: (doctorId: number | string) =>
      `/patient-portal/doctors/${doctorId}/availability/`,
    prescriptions: '/patient-portal/prescriptions/',
    prescription: (id: number | string) => `/patient-portal/prescriptions/${id}/`,
    invoices: '/patient-portal/invoices/',
    invoice: (id: number | string) => `/patient-portal/invoices/${id}/`,
    documents: '/patient-portal/documents/',
    document: (id: number | string) => `/patient-portal/documents/${id}/`,
    documentDownload: (id: number | string) => `/patient-portal/documents/${id}/download/`,
    documentPreview: (id: number | string) => `/patient-portal/documents/${id}/preview/`,
    notifications: '/patient-portal/notifications/',
    unreadNotifications: '/patient-portal/notifications/unread-count/',
    payments: '/patient-portal/payments/',
    medicalOrders: '/patient-portal/medical-orders/',
    medicalOrder: (id: number | string) => `/patient-portal/medical-orders/${id}/`,
  },
  notifications: {
    markRead: (id: number | string) => `/notifications/${id}/mark-read/`,
  },
} as const;
