# Generated by Django 5.2.15 on 2026-06-08 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('prescription_number', models.CharField(max_length=30)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('general_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('void_reason', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinics.clinic')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.clinicalconsultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'ordering': ['-issue_date', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=180)),
                ('presentation', models.CharField(blank=True, max_length=120)),
                ('dosage', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=120)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('intravenosa', 'Intravenosa'), ('intramuscular', 'Intramuscular'), ('subcutanea', 'Subcutanea'), ('topica', 'Topica'), ('inhalada', 'Inhalada'), ('oftalmica', 'Oftalmica'), ('otica', 'Otica'), ('nasal', 'Nasal'), ('otra', 'Otra')], default='oral', max_length=30)),
                ('instructions', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('diagnosis_type', models.CharField(choices=[('presuntivo', 'Presuntivo'), ('confirmado', 'Confirmado'), ('diferencial', 'Diferencial')], default='presuntivo', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='clinics.clinic')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical_records.clinicalconsultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
                'indexes': [models.Index(fields=['clinic', 'patient'], name='prescriptio_clinic__a24b34_idx'), models.Index(fields=['consultation', 'is_primary'], name='prescriptio_consult_d47c64_idx'), models.Index(fields=['diagnosis_type'], name='prescriptio_diagnos_89877d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=30)),
                ('order_type', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagenologia', 'Imagenologia'), ('procedimiento', 'Procedimiento'), ('interconsulta', 'Interconsulta'), ('otro', 'Otro')], default='laboratorio', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_orders', to='clinics.clinic')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_orders', to='medical_records.clinicalconsultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_orders', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinic', 'order_number'], name='prescriptio_clinic__3f4495_idx'), models.Index(fields=['patient', 'creado_en'], name='prescriptio_patient_195af5_idx'), models.Index(fields=['doctor', 'creado_en'], name='prescriptio_doctor__0e10ed_idx'), models.Index(fields=['order_type'], name='prescriptio_order_t_b2f321_idx'), models.Index(fields=['status'], name='prescriptio_status_ad21e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'order_number'), name='unique_order_number_per_clinic')],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', 'prescription_number'], name='prescriptio_clinic__3d6e89_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'issue_date'], name='prescriptio_patient_6673cb_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'issue_date'], name='prescriptio_doctor__5323a3_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='prescriptio_status_940ca9_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('clinic', 'prescription_number'), name='unique_prescription_number_per_clinic'),
        ),
    ]
