export type PurchaseOrderStatus = "borrador" | "pendiente" | "aprobada" | "recibida_parcial" | "recibida" | "cancelada";

export interface Supplier { id: number; clinic: number; clinic_nombre?: string; name: string; rtn: string; contact_name: string; phone: string; email: string; address: string; city: string; country: string; notes: string; active: boolean; creado_en: string; actualizado_en: string; total_purchased?: string; last_purchase?: string | null; }
export interface PurchaseOrderItem { id: number; purchase_order: number; item: number; item_nombre?: string; item_sku?: string; requires_lot?: boolean; requires_expiration?: boolean; description: string; quantity_ordered: string; quantity_received: string; pending_quantity: string; unit_cost: string; discount_amount: string; tax_rate: string; tax_amount: string; line_total: string; active: boolean; }
export interface PurchaseReceiptItem { id: number; receipt: number; purchase_order_item: number; order_item_description?: string; item: number; item_nombre?: string; lot: number | null; quantity_received: string; unit_cost: string; lot_number: string; expiration_date: string | null; notes: string; inventory_movement: number | null; active: boolean; creado_en: string; }
export interface PurchaseReceipt { id: number; clinic: number; purchase_order: number; order_number?: string; supplier_nombre?: string; receipt_number: string; receipt_date: string; received_by: number | null; received_by_nombre?: string; notes: string; active: boolean; creado_en: string; items?: PurchaseReceiptItem[]; }
export interface PurchaseOrder { id: number; clinic: number; supplier: number; supplier_nombre?: string; order_number: string; order_date: string; expected_date: string | null; status: PurchaseOrderStatus; subtotal: string; discount_amount: string; tax_amount: string; total_amount: string; notes: string; created_by: number | null; created_by_nombre?: string; approved_by?: number | null; approved_by_nombre?: string; approved_at?: string | null; cancelled_by?: number | null; cancelled_by_nombre?: string; cancelled_at?: string | null; cancellation_reason?: string; active: boolean; creado_en: string; items?: PurchaseOrderItem[]; receipts?: PurchaseReceipt[]; }
export interface PurchaseStats { total_purchase_orders: number; draft_orders: number; pending_orders: number; approved_orders: number; partially_received_orders: number; received_orders: number; cancelled_orders: number; total_purchased_amount: string; purchases_this_month: string; total_suppliers: number; active_suppliers: number; }

