# Generated by Django 5.2.15 on 2026-06-09 16:59

import apps.documents.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('billing', '0002_remove_billableservice_unique_service_code_per_clinic_and_more'),
        ('clinics', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('clinical', 'Clinico'), ('administrative', 'Administrativo'), ('billing', 'Facturacion'), ('identity', 'Identidad'), ('consent', 'Consentimiento'), ('lab_result', 'Resultado laboratorio'), ('imaging', 'Imagen medica'), ('prescription', 'Receta'), ('medical_order', 'Orden medica'), ('other', 'Otro')], default='other', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='clinics.clinic')),
            ],
            options={
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=apps.documents.utils.clinical_document_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=80)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('external', 'Externo')], default='local', max_length=20)),
                ('visible_to_patient', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado'), ('deleted', 'Eliminado')], default='active', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents', to='clinics.clinic')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medical_records.clinicalconsultation')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='billing.invoice')),
                ('medical_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='prescriptions.medicalorder')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_documents', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='prescriptions.prescription')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='documents.clinicaldocument')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('clinic', 'name', 'document_type'), name='unique_document_category_per_clinic_type'),
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('clinic__isnull', True)), fields=('name', 'document_type'), name='unique_global_document_category_type'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['clinic', 'patient', 'status'], name='documents_c_clinic__cad408_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['category', 'creado_en'], name='documents_c_categor_8b912b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['visible_to_patient', 'status'], name='documents_c_visible_dd5bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['is_sensitive'], name='documents_c_is_sens_b7e13e_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaldocument',
            index=models.Index(fields=['uploaded_by'], name='documents_c_uploade_8b3aeb_idx'),
        ),
    ]
