# Generated by Django 5.2.15 on 2026-06-09 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_doctors', models.PositiveIntegerField(default=2)),
                ('max_patients', models.PositiveIntegerField(default=300)),
                ('max_appointments_per_month', models.PositiveIntegerField(default=200)),
                ('max_storage_mb', models.PositiveIntegerField(default=1000)),
                ('allow_billing', models.BooleanField(default=True)),
                ('allow_inventory', models.BooleanField(default=False)),
                ('allow_purchases', models.BooleanField(default=False)),
                ('allow_reports', models.BooleanField(default=True)),
                ('allow_audit', models.BooleanField(default=False)),
                ('allow_notifications', models.BooleanField(default=True)),
                ('allow_patient_portal', models.BooleanField(default=False)),
                ('allow_mobile_api', models.BooleanField(default=True)),
                ('allow_multi_branch', models.BooleanField(default=False)),
                ('support_level', models.CharField(choices=[('basic', 'Basico'), ('priority', 'Prioritario'), ('enterprise', 'Empresarial')], default='basic', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_monthly', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Activa'), ('past_due', 'Pago vencido'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada'), ('expired', 'Expirada')], default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['clinic__nombre'],
            },
        ),
    ]
