# Generated by Django 5.2.15 on 2026-06-08 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('item_type', models.CharField(choices=[('medicamento', 'Medicamento'), ('insumo', 'Insumo'), ('equipo', 'Equipo'), ('material', 'Material'), ('laboratorio', 'Laboratorio'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('unit', models.CharField(default='unidad', max_length=40)),
                ('presentation', models.CharField(blank=True, max_length=120)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_current', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_maximum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requires_lot', models.BooleanField(default=False)),
                ('requires_expiration', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='clinics.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=80)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quantity_current', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='clinics.clinic')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['expiration_date', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('devolucion', 'Devolucion'), ('perdida', 'Perdida'), ('vencimiento', 'Vencimiento')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(max_length=180)),
                ('reference_type', models.CharField(blank=True, max_length=60)),
                ('reference_id', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='clinics.clinic')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorylot')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_inventory_category_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('clinic', 'sku'), name='unique_inventory_sku_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('clinic', 'barcode'), name='unique_inventory_barcode_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(fields=('item', 'lot_number'), name='unique_lot_number_per_item'),
        ),
    ]
