# Generated by Django 5.2.15 on 2026-07-29 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_movement_balances(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    InventoryLot = apps.get_model("inventory", "InventoryLot")
    InventoryMovement = apps.get_model("inventory", "InventoryMovement")
    positive_types = {"entrada", "ajuste_positivo", "devolucion"}

    for item in InventoryItem.objects.all().iterator():
        current = item.stock_current
        movements = list(InventoryMovement.objects.filter(item_id=item.id).order_by("-creado_en", "-id"))
        for movement in movements:
            movement.balance_after = max(current, 0)
            before = current - movement.quantity if movement.movement_type in positive_types else current + movement.quantity
            movement.balance_before = max(before, 0)
            current = before
        if movements:
            InventoryMovement.objects.bulk_update(movements, ["balance_before", "balance_after"], batch_size=500)

    for lot in InventoryLot.objects.all().iterator():
        current = lot.quantity_current
        movements = list(InventoryMovement.objects.filter(lot_id=lot.id).order_by("-creado_en", "-id"))
        for movement in movements:
            movement.lot_balance_after = max(current, 0)
            before = current - movement.quantity if movement.movement_type in positive_types else current + movement.quantity
            movement.lot_balance_before = max(before, 0)
            current = before
        if movements:
            InventoryMovement.objects.bulk_update(movements, ["lot_balance_before", "lot_balance_after"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='lot_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='lot_balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reversed_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movements', to='inventory.inventorymovement'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('devolucion', 'Devolucion'), ('devolucion_proveedor', 'Devolucion a proveedor'), ('reversion', 'Reversion'), ('perdida', 'Perdida'), ('vencimiento', 'Vencimiento')], max_length=30),
        ),
        migrations.RunPython(backfill_movement_balances, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('stock_current__gte', 0)), name='inventory_item_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimum__gte', 0)), name='inventory_item_minimum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('stock_maximum__gte', 0)), name='inventory_item_maximum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='inventory_item_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='inventory_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_current__gte', 0)), name='inventory_lot_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='inventory_lot_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0)), name='inventory_movement_before_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='inventory_movement_after_nonnegative'),
        ),
    ]
