export type ReceptionAppointment = {
  id?: number;
  patient_id?: number;
  patient?: number;
  patient_name?: string;
  patient_nombre?: string;
  doctor_id?: number;
  doctor?: number;
  doctor_name?: string;
  doctor_nombre?: string;
  date?: string;
  scheduled_date?: string;
  time?: string;
  scheduled_time?: string;
  datetime?: string;
  modality?: 'presencial' | 'online' | string;
  status?: string;
  cancellation_reason?: string;
  no_show_reason?: string;
  reason?: string;
  motivo?: string;
  visit?: number | Record<string, unknown> | null;
  visit_id?: number | null;
  admission?: number | Record<string, unknown> | null;
  admission_id?: number | null;
  check_in_visit_id?: number | null;
  checked_in?: boolean;
};
