# Generated by Django 5.2.15 on 2026-06-19 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_patientvisit_billing_started_at_and_more'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('medical_records', '0003_clinicalconsultation_patient_visit_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bed_number', models.CharField(max_length=40)),
                ('bed_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('cleaning', 'Limpieza'), ('maintenance', 'Mantenimiento'), ('blocked', 'Bloqueada')], default='available', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_beds', to='clinics.clinic')),
            ],
            options={
                'ordering': ['room__room_number', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('admission_source', models.CharField(choices=[('consultation', 'Consulta'), ('emergency', 'Emergencia'), ('reception', 'Recepcion'), ('transfer', 'Traslado'), ('other', 'Otro')], default='reception', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('observation', 'Observacion'), ('transferred', 'Trasladado'), ('discharged', 'Alta'), ('cancelled', 'Cancelado')], default='active', max_length=30)),
                ('reason', models.TextField()),
                ('diagnosis_at_admission', models.TextField(blank=True)),
                ('admission_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_datetime', models.DateTimeField(blank=True, null=True)),
                ('discharge_reason', models.TextField(blank=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('transfer_notes', models.TextField(blank=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations_admitted', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='clinics.clinic')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to='medical_records.clinicalconsultation')),
                ('current_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_hospitalizations', to='hospitalization.hospitalbed')),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations_discharged', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='patients.patient')),
                ('responsible_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to='doctors.doctorprofile')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizations', to='admissions.patientvisit')),
            ],
            options={
                'ordering': ['-admission_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HospitalBedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_bed_assignments', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hospitalization.hospitalbed')),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='hospitalization.hospitalization')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalization_events', to=settings.AUTH_USER_MODEL)),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hospitalization.hospitalization')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HospitalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('room_number', models.CharField(max_length=40)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('room_type', models.CharField(choices=[('general', 'General'), ('private', 'Privada'), ('emergency', 'Emergencia'), ('observation', 'Observacion'), ('pediatric', 'Pediatria'), ('maternity', 'Maternidad'), ('intensive_care', 'Cuidados intensivos'), ('other', 'Otro')], default='general', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_rooms', to='clinics.clinic')),
            ],
            options={
                'ordering': ['clinic', 'room_number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hospitalbed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hospitalization.hospitalroom'),
        ),
        migrations.CreateModel(
            name='HospitalVitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glucose', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pain_scale', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='hospitalization.hospitalization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('normal', 'Normal'), ('important', 'Importante'), ('urgent', 'Urgente'), ('medication', 'Medicamento'), ('observation', 'Observacion'), ('incident', 'Incidente')], default='normal', max_length=30)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes', to=settings.AUTH_USER_MODEL)),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='hospitalization.hospitalization')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hospitalization',
            index=models.Index(fields=['clinic', 'status'], name='hospitaliza_clinic__fa6b03_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalization',
            index=models.Index(fields=['patient', 'status'], name='hospitaliza_patient_dedcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalization',
            index=models.Index(fields=['current_bed', 'status'], name='hospitaliza_current_99cbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalization',
            index=models.Index(fields=['admission_datetime'], name='hospitaliza_admissi_05abce_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalization',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'observation', 'transferred'])), fields=('clinic', 'patient'), name='unique_active_hospitalization_per_patient_clinic'),
        ),
        migrations.AddIndex(
            model_name='hospitalbedassignment',
            index=models.Index(fields=['hospitalization', 'assigned_at'], name='hospitaliza_hospita_fa2772_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbedassignment',
            index=models.Index(fields=['bed', 'released_at'], name='hospitaliza_bed_id_753999_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalizationevent',
            index=models.Index(fields=['hospitalization', 'event_type'], name='hospitaliza_hospita_929a05_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalizationevent',
            index=models.Index(fields=['event_type', 'creado_en'], name='hospitaliza_event_t_c631ee_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalroom',
            index=models.Index(fields=['clinic', 'is_active'], name='hospitaliza_clinic__f9061a_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalroom',
            index=models.Index(fields=['room_type'], name='hospitaliza_room_ty_3e1743_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalroom',
            constraint=models.UniqueConstraint(fields=('clinic', 'room_number'), name='unique_hospital_room_number_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='hospitalbed',
            index=models.Index(fields=['clinic', 'status', 'is_active'], name='hospitaliza_clinic__1a21c4_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbed',
            index=models.Index(fields=['room', 'status'], name='hospitaliza_room_id_df8134_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalbed',
            constraint=models.UniqueConstraint(fields=('clinic', 'bed_code'), name='unique_hospital_bed_code_per_clinic'),
        ),
        migrations.AddIndex(
            model_name='hospitalvitalsigns',
            index=models.Index(fields=['hospitalization', 'recorded_at'], name='hospitaliza_hospita_1cafa1_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingnote',
            index=models.Index(fields=['hospitalization', 'recorded_at'], name='hospitaliza_hospita_483155_idx'),
        ),
        migrations.AddIndex(
            model_name='nursingnote',
            index=models.Index(fields=['note_type'], name='hospitaliza_note_ty_141b01_idx'),
        ),
    ]
