# Generated by Django 5.2.15 on 2026-06-19 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('hospitalization', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('medication_name', models.CharField(max_length=180)),
                ('dosage', models.CharField(max_length=120)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenosa'), ('im', 'Intramuscular'), ('sc', 'Subcutanea'), ('topical', 'Topica'), ('inhaled', 'Inhalada'), ('other', 'Otra')], default='oral', max_length=30)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('administered_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('administered', 'Administrado'), ('omitted', 'Omitido'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('omission_reason', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_administrations_done', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_administrations', to='clinics.clinic')),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='hospitalization.hospitalization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_administrations', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_administrations', to='prescriptions.prescription')),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_administrations', to='prescriptions.prescriptionitem')),
            ],
            options={
                'ordering': ['scheduled_time', '-creado_en'],
                'indexes': [models.Index(fields=['clinic', 'status', 'scheduled_time'], name='hospitaliza_clinic__9a1797_idx'), models.Index(fields=['hospitalization', 'status'], name='hospitaliza_hospita_18ae1a_idx'), models.Index(fields=['patient', 'status'], name='hospitaliza_patient_64b667_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('round_type', models.CharField(choices=[('routine', 'Rutina'), ('urgent', 'Urgente'), ('medication', 'Medicacion'), ('follow_up', 'Seguimiento'), ('other', 'Otro')], default='routine', max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Completada'), ('pending_review', 'Pendiente de revision'), ('cancelled', 'Cancelada')], default='completed', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('general_condition', models.CharField(blank=True, max_length=180)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consciousness_status', models.CharField(blank=True, max_length=120)),
                ('mobility_status', models.CharField(blank=True, max_length=120)),
                ('feeding_status', models.CharField(blank=True, max_length=120)),
                ('elimination_status', models.CharField(blank=True, max_length=120)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_rounds', to='clinics.clinic')),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_rounds', to='hospitalization.hospitalization')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_rounds', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_rounds', to='patients.patient')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['clinic', 'creado_en'], name='hospitaliza_clinic__9f76fc_idx'), models.Index(fields=['hospitalization', 'creado_en'], name='hospitaliza_hospita_b4b34c_idx'), models.Index(fields=['patient', 'creado_en'], name='hospitaliza_patient_a7d8e6_idx'), models.Index(fields=['round_type', 'status'], name='hospitaliza_round_t_5c16db_idx')],
            },
        ),
    ]
