# Generated by Django 5.2.15 on 2026-07-29 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_patientvisit_unique_visit_per_appointment'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('hospitalization', '0002_medicationadministration_nursinground'),
        ('medical_records', '0005_clinicalsupplyusage_cancellation_reason_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmada'), ('correction', 'Correccion')], default='draft', max_length=20)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('diagnosis_changes', models.TextField(blank=True)),
                ('treatment_changes', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MedicalInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('instruction_type', models.CharField(choices=[('medication', 'Medicamento'), ('monitoring', 'Monitorizacion'), ('diet', 'Dieta'), ('activity', 'Actividad'), ('procedure', 'Procedimiento'), ('wound_care', 'Curacion'), ('vital_signs', 'Control de signos'), ('laboratory', 'Laboratorio'), ('imaging', 'Imagen'), ('other', 'Otra')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('routine', 'Rutina'), ('urgent', 'Urgente'), ('stat', 'Inmediata')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('acknowledged', 'Leida'), ('in_progress', 'En proceso'), ('completed', 'Completada'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField()),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-effective_from', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('replaced', 'Reemplazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('goals', models.TextField(blank=True)),
                ('treatment', models.TextField()),
                ('monitoring', models.TextField(blank=True)),
                ('diet', models.TextField(blank=True)),
                ('activity', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('expected_duration', models.CharField(blank=True, max_length=120)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-version', '-creado_en'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='hospitalization',
            name='unique_active_hospitalization_per_patient_clinic',
        ),
        migrations.AddField(
            model_name='hospitalbedassignment',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_bed_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='expected_discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitalizationevent',
            name='event_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hospitalizationevent',
            name='severity',
            field=models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Critico')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='hospitalvitalsigns',
            name='alert_summary',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='hospitalvitalsigns',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospitalvitalsigns',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalvitalsigns',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_vital_alerts_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='hospitalization.nursingnote'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='shift',
            field=models.CharField(choices=[('morning', 'Manana'), ('afternoon', 'Tarde'), ('night', 'Noche'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='status',
            field=models.CharField(choices=[('signed', 'Firmada'), ('correction', 'Correccion')], default='signed', max_length=20),
        ),
        migrations.AddField(
            model_name='nursinground',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursinground',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nursinground',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursinground',
            name='status_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='hospitalization',
            name='status',
            field=models.CharField(choices=[('pending_admission', 'Pendiente de ingreso'), ('active', 'Activo'), ('observation', 'Observacion'), ('transferred', 'Trasladado'), ('discharge_pending', 'Alta pendiente'), ('discharged', 'Alta'), ('cancelled', 'Cancelado')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='nursinground',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('missed', 'Omitida'), ('pending_review', 'Pendiente de revision'), ('cancelled', 'Cancelada')], default='completed', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='hospitalbedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('bed',), name='unique_active_assignment_per_bed'),
        ),
        migrations.AddConstraint(
            model_name='hospitalbedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('hospitalization',), name='unique_active_assignment_per_hospitalization'),
        ),
        migrations.AddConstraint(
            model_name='hospitalization',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_admission', 'active', 'observation', 'transferred', 'discharge_pending'])), fields=('clinic', 'patient'), name='unique_active_hospitalization_per_patient_clinic'),
        ),
        migrations.AddConstraint(
            model_name='hospitalization',
            constraint=models.UniqueConstraint(fields=('clinic', 'admitted_by', 'idempotency_key'), name='unique_hospitalization_operation'),
        ),
        migrations.AddConstraint(
            model_name='nursinground',
            constraint=models.UniqueConstraint(fields=('clinic', 'nurse', 'idempotency_key'), name='unique_nursing_round_operation'),
        ),
        migrations.AddField(
            model_name='medicalevolution',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='hospitalization.medicalevolution'),
        ),
        migrations.AddField(
            model_name='medicalevolution',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_evolutions', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalevolution',
            name='hospitalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_evolutions', to='hospitalization.hospitalization'),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_instructions_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_instructions_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_instructions', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='hospitalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_instructions', to='hospitalization.hospitalization'),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='hospitalization.medicalinstruction'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_treatment_plans', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='hospitalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='hospitalization.hospitalization'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='hospitalization.treatmentplan'),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructions', to='hospitalization.treatmentplan'),
        ),
        migrations.AddIndex(
            model_name='medicalevolution',
            index=models.Index(fields=['hospitalization', 'status', 'creado_en'], name='hospitaliza_hospita_65e5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalevolution',
            index=models.Index(fields=['doctor', 'creado_en'], name='hospitaliza_doctor__2e0286_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['hospitalization', 'status'], name='hospitaliza_hospita_006dea_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentplan',
            constraint=models.UniqueConstraint(fields=('hospitalization', 'version'), name='unique_treatment_plan_version'),
        ),
        migrations.AddIndex(
            model_name='medicalinstruction',
            index=models.Index(fields=['hospitalization', 'status', 'priority'], name='hospitaliza_hospita_3fb293_idx'),
        ),
    ]
