# Generated by Django 5.2.15 on 2026-07-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('hospitalization', '0003_medicalevolution_medicalinstruction_treatmentplan_and_more'),
        ('inventory', '0002_inventorymovement_balance_after_and_more'),
        ('patients', '0001_initial'),
        ('prescriptions', '0002_medicalorder_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('signed', 'Firmado'), ('replaced', 'Reemplazado')], default='draft', max_length=20)),
                ('discharge_type', models.CharField(choices=[('medical', 'Alta medica'), ('voluntary', 'Alta voluntaria'), ('transfer', 'Traslado'), ('death', 'Defuncion'), ('abandonment', 'Abandono'), ('other', 'Otra')], default='medical', max_length=20)),
                ('admission_summary', models.TextField(blank=True)),
                ('hospital_course', models.TextField()),
                ('discharge_diagnoses', models.TextField()),
                ('procedures', models.TextField(blank=True)),
                ('relevant_findings', models.TextField(blank=True)),
                ('condition_at_discharge', models.TextField()),
                ('treatment_at_discharge', models.TextField(blank=True)),
                ('recommendations', models.TextField()),
                ('warning_signs', models.TextField(blank=True)),
                ('follow_up_plan', models.TextField()),
                ('pending_results', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('correction_reason', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-version', '-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='allergy_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='allergy_warning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='as_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='concentration',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='dose_unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='generic_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_medical_instructions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='inventory_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='maximum_daily_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='route',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='medicalinstruction',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='administered_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='administered_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='administration_idempotency_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='delay_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='dose_unit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='hospitalization.medicalinstruction'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_medication_administrations', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='inventory_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='inventory_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='ordered_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='refusal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_medication_administrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='selected_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_medication_administrations', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='unavailable_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Programada'), ('due', 'Por administrar'), ('administered', 'Administrado'), ('omitted', 'Omitido'), ('refused', 'Rechazado'), ('unavailable', 'No disponible'), ('delayed', 'Retrasado'), ('cancelled', 'Cancelado'), ('reversed', 'Revertido')], default='pending', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='medicationadministration',
            constraint=models.UniqueConstraint(condition=models.Q(('instruction__isnull', False), ('scheduled_time__isnull', False)), fields=('instruction', 'scheduled_time'), name='unique_instruction_medication_schedule'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital_discharge_summaries', to='doctors.doctorprofile'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='hospitalization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries', to='hospitalization.hospitalization'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_discharge_summaries', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_summaries', to='hospitalization.dischargesummary'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_hospital_discharge_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dischargesummary',
            constraint=models.UniqueConstraint(fields=('hospitalization', 'version'), name='unique_discharge_summary_version'),
        ),
    ]
