# Generated by Django 5.2.15 on 2026-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalization', '0004_dischargesummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='status_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
