# Generated by Django 5.2.15 on 2026-07-30 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('hospitalization', '0005_medication_status_timestamp'),
        ('inventory', '0002_inventorymovement_balance_after_and_more'),
        ('patients', '0001_initial'),
        ('prescriptions', '0002_medicalorder_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicationadministration',
            name='unique_instruction_medication_schedule',
        ),
        migrations.AddConstraint(
            model_name='medicationadministration',
            constraint=models.UniqueConstraint(fields=('instruction', 'scheduled_time'), name='unique_instruction_medication_schedule'),
        ),
    ]
