# Generated by Django 5.2.15 on 2026-06-08 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_paciente', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('nombre_completo', models.CharField(blank=True, max_length=250)),
                ('identidad', models.CharField(blank=True, max_length=40)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_especificado', 'No especificado')], default='no_especificado', max_length=30)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('departamento', models.CharField(blank=True, max_length=80)),
                ('pais', models.CharField(blank=True, default='Honduras', max_length=80)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=160)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=30)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=80)),
                ('alergias', models.TextField(blank=True)),
                ('enfermedades_cronicas', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='clinics.clinic')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre_completo'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'codigo_paciente'), name='unique_patient_code_per_clinic'), models.UniqueConstraint(condition=models.Q(('identidad', ''), _negated=True), fields=('clinic', 'identidad'), name='unique_patient_identity_per_clinic')],
            },
        ),
    ]
