export type PatientPayment = {
  id: number;
  invoice?: number;
  invoice_number?: string;
  clinic_nombre?: string;
  payment_number?: string;
  payment_date?: string;
  amount?: string | number;
  method?: string;
  method_display?: string;
  reference_visible?: string | null;
  notes?: string | null;
  status?: string;
  status_display?: string;
  balance_before?: string | number;
  balance_after?: string | number;
  receipt_available?: boolean;
  receipt_url?: string;
  creado_en?: string;
  actualizado_en?: string;
};
