# Generated by Django 5.2.15 on 2026-06-09 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login exitoso'), ('login_failed', 'Login fallido'), ('logout', 'Logout'), ('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('activate', 'Activar'), ('deactivate', 'Desactivar'), ('view', 'Ver'), ('export', 'Exportar'), ('approve', 'Aprobar'), ('cancel', 'Cancelar'), ('void', 'Anular'), ('finalize', 'Finalizar'), ('issue', 'Emitir'), ('payment', 'Pago'), ('stock_in', 'Entrada stock'), ('stock_out', 'Salida stock'), ('stock_adjustment', 'Ajuste stock'), ('purchase_receive', 'Recepcion compra'), ('password_change', 'Cambio contrasena'), ('password_reset', 'Reset contrasena'), ('permission_denied', 'Permiso denegado'), ('system_error', 'Error sistema')], max_length=40)),
                ('module', models.CharField(choices=[('auth', 'Auth'), ('users', 'Usuarios'), ('clinics', 'Clinicas'), ('doctors', 'Medicos'), ('patients', 'Pacientes'), ('appointments', 'Citas'), ('medical_records', 'Expedientes'), ('consultations', 'Consultas'), ('prescriptions', 'Recetas'), ('billing', 'Facturacion'), ('payments', 'Pagos'), ('cash', 'Caja'), ('inventory', 'Inventario'), ('purchases', 'Compras'), ('reports', 'Reportes'), ('settings', 'Configuracion'), ('system', 'Sistema')], max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('object_repr', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=12)),
                ('request_path', models.CharField(blank=True, max_length=300)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='clinics.clinic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='audit_audit_clinic__f6afa8_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['module'], name='audit_audit_module_e8d32b_idx'), models.Index(fields=['severity'], name='audit_audit_severit_f33e16_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx')],
            },
        ),
    ]
