# Generated by Django 5.2.15 on 2026-06-18 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='after_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('warning', 'Advertencia')], db_index=True, default='success', max_length=30),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_success', 'Login exitoso'), ('login_failed', 'Login fallido'), ('logout', 'Logout'), ('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('activate', 'Activar'), ('deactivate', 'Desactivar'), ('view', 'Ver'), ('export', 'Exportar'), ('print', 'Imprimir'), ('download', 'Descargar'), ('approve', 'Aprobar'), ('reject', 'Rechazar'), ('cancel', 'Cancelar'), ('void', 'Anular'), ('complete', 'Completar'), ('finalize', 'Finalizar'), ('issue', 'Emitir'), ('invoice', 'Facturar'), ('payment', 'Pago'), ('pay', 'Pagar'), ('stock_in', 'Entrada stock'), ('stock_out', 'Salida stock'), ('stock_adjustment', 'Ajuste stock'), ('purchase_receive', 'Recepcion compra'), ('password_change', 'Cambio contrasena'), ('password_reset', 'Reset contrasena'), ('permission_change', 'Cambio permisos'), ('settings_change', 'Cambio configuracion'), ('permission_denied', 'Permiso denegado'), ('system_error', 'Error sistema')], db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('auth', 'Auth'), ('users', 'Usuarios'), ('clinics', 'Clinicas'), ('doctors', 'Medicos'), ('patients', 'Pacientes'), ('appointments', 'Citas'), ('admissions', 'Admisiones'), ('triage', 'Triaje'), ('medical_records', 'Expedientes'), ('consultations', 'Consultas'), ('prescriptions', 'Recetas'), ('medical_orders', 'Ordenes medicas'), ('billing', 'Facturacion'), ('payments', 'Pagos'), ('cash', 'Caja'), ('inventory', 'Inventario'), ('purchases', 'Compras'), ('documents', 'Documentos'), ('reports', 'Reportes'), ('settings', 'Configuracion'), ('subscriptions', 'Suscripciones'), ('security', 'Seguridad'), ('system', 'Sistema')], db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'created_at'], name='audit_audit_module_fb6a54_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_effc12_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status', 'created_at'], name='audit_audit_status_919dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'),
        ),
    ]
