# Generated by Django 5.2.15 on 2026-06-11 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('billing', '0004_invoiceitem_related_consumption'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('medical_records', '0002_clinicalsupplyusage'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('visit_number', models.CharField(max_length=30)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('triage_started_at', models.DateTimeField(blank=True, null=True)),
                ('triage_completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('visit_type', models.CharField(choices=[('walk_in', 'Sin cita'), ('appointment', 'Cita'), ('emergency', 'Emergencia'), ('follow_up', 'Seguimiento'), ('control', 'Control'), ('procedure', 'Procedimiento')], default='walk_in', max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Prioritario'), ('urgent', 'Urgente'), ('emergency', 'Emergencia')], default='normal', max_length=30)),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('waiting_triage', 'Esperando triaje'), ('in_triage', 'En triaje'), ('waiting_doctor', 'Esperando doctor'), ('in_consultation', 'En consulta'), ('waiting_billing', 'Pendiente de cobro'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('no_show', 'No asistio')], default='waiting_triage', max_length=30)),
                ('reason', models.CharField(max_length=250)),
                ('symptoms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='appointments.appointment')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to='doctors.doctorprofile')),
                ('assigned_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_triage_visits', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_checked_in', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_visits', to='clinics.clinic')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visits', to='medical_records.clinicalconsultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visits', to='billing.invoice')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-arrival_time'],
                'indexes': [models.Index(fields=['clinic', 'visit_date'], name='admissions__clinic__ef3c6d_idx'), models.Index(fields=['patient', 'visit_date'], name='admissions__patient_da01dc_idx'), models.Index(fields=['status'], name='admissions__status_0a1611_idx'), models.Index(fields=['priority'], name='admissions__priorit_c861e2_idx'), models.Index(fields=['assigned_doctor', 'status'], name='admissions__assigne_17d28c_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'visit_number'), name='unique_visit_number_per_clinic')],
            },
        ),
    ]
