# Generated by Django 5.2.15 on 2026-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='billing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='origin',
            field=models.CharField(choices=[('reception', 'Recepcion'), ('patient_portal', 'Portal paciente'), ('doctor', 'Medico'), ('import', 'Importacion')], default='reception', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='status',
            field=models.CharField(choices=[('registered', 'Registrado'), ('waiting_triage', 'Esperando triaje'), ('in_triage', 'En triaje'), ('waiting_doctor', 'Esperando doctor'), ('in_consultation', 'En consulta'), ('consultation_finished', 'Consulta finalizada'), ('waiting_billing', 'Pendiente de cobro'), ('waiting_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('no_show', 'No asistio')], default='waiting_triage', max_length=30),
        ),
    ]
