# Generated by Django 5.2.15 on 2026-07-22 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_patientvisit_billing_started_at_and_more'),
        ('appointments', '0002_appointment_modality'),
        ('billing', '0008_creditnote'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        ('medical_records', '0003_clinicalconsultation_patient_visit_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patientvisit',
            constraint=models.UniqueConstraint(fields=('appointment',), name='unique_visit_per_appointment'),
        ),
    ]
