# Generated by Django 5.2.15 on 2026-07-29 04:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('inventory', '0002_inventorymovement_balance_after_and_more'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('return_number', models.CharField(blank=True, max_length=30)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('revertida', 'Revertida')], default='confirmada', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-return_date', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('quantity_returned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='quantity_returned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('clinic', 'purchase_order', 'received_by', 'idempotency_key'), name='unique_purchase_receipt_operation'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='inventory_movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchases.purchasereturn'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='receipt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='purchases.purchasereceiptitem'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('clinic', 'return_number'), name='unique_purchase_return_number_per_clinic'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('clinic', 'receipt', 'created_by', 'idempotency_key'), name='unique_purchase_return_operation'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_returned__gt', 0)), name='purchase_return_quantity_positive'),
        ),
    ]
