# Generated by Django 5.2.15 on 2026-06-08 05:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_colegiacion', models.CharField(max_length=80)),
                ('titulo_profesional', models.CharField(blank=True, max_length=180)),
                ('biografia', models.TextField(blank=True)),
                ('tarifa_consulta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('duracion_consulta_minutos', models.PositiveIntegerField(default=30)),
                ('atiende_virtual', models.BooleanField(default=False)),
                ('atiende_presencial', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profiles', to='clinics.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profiles', to='doctors.medicalspecialty')),
            ],
            options={
                'ordering': ['user__nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['doctor', 'dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'dia_semana', 'hora_inicio', 'hora_fin'), name='unique_exact_doctor_schedule')],
            },
        ),
        migrations.AddConstraint(
            model_name='doctorprofile',
            constraint=models.UniqueConstraint(fields=('clinic', 'numero_colegiacion'), name='unique_doctor_license_per_clinic'),
        ),
    ]
