# Generated by Django 5.2.15 on 2026-06-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='modality',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'En línea')], db_index=True, default='presencial', max_length=20),
        ),
    ]
