# Generated by Django 5.2.15 on 2026-06-09 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('receive_appointment_reminders', models.BooleanField(default=True)),
                ('receive_billing_alerts', models.BooleanField(default=True)),
                ('receive_inventory_alerts', models.BooleanField(default=True)),
                ('receive_purchase_alerts', models.BooleanField(default=True)),
                ('receive_audit_alerts', models.BooleanField(default=True)),
                ('receive_system_notifications', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('module', models.CharField(choices=[('system', 'System'), ('auth', 'Auth'), ('appointments', 'Appointments'), ('patients', 'Patients'), ('doctors', 'Doctors'), ('medical_records', 'Medical records'), ('consultations', 'Consultations'), ('prescriptions', 'Prescriptions'), ('billing', 'Billing'), ('payments', 'Payments'), ('cash', 'Cash'), ('inventory', 'Inventory'), ('purchases', 'Purchases'), ('reports', 'Reports'), ('audit', 'Audit')], default='system', max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=20)),
                ('related_model', models.CharField(blank=True, max_length=120)),
                ('related_object_id', models.CharField(blank=True, max_length=80)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clinics.clinic')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['recipient', 'status', 'creado_en'], name='notificatio_recipie_c091e4_idx'), models.Index(fields=['clinic', 'creado_en'], name='notificatio_clinic__e1db32_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx'), models.Index(fields=['module'], name='notificatio_module_157451_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['read_at'], name='notificatio_read_at_6329f9_idx')],
            },
        ),
    ]
