# Generated by Django 5.2.15 on 2026-07-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushdevice'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='installation_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
